### ISSUE TITLE
Exception when task tag support tries to visit not exisitng file

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-commons#28]
```
java.lang.Exception: File not found: /home/albert/Desktop/test.adoc.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:833)
	at org.eclipse.core.internal.resources.File.getContents(File.java:280)
	at org.eclipse.core.internal.resources.File.getContents(File.java:271)
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.visitResource(TaskTagsSupport.java:343)
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.doNoResourceChangedScan(TaskTagsSupport.java:155)
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.doNoResourceChangedScan(TaskTagsSupport.java:128)
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.noResourceChangedScan(TaskTagsSupport.java:114)
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.install(TaskTagsSupport.java:93)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditorActivator.start(AsciiDoctorEditorActivator.java:74)
```
Happend at start of asciidoctor. I am not sure if this makes problems on task tag handling.
It was a linked file . So maybe the file.exists() did not work as expected.
Also TaskTagSupport should catch `Exception` and not only IO + Runtime.
And one failure should not exit all

**Comment by de-jcup** [comment]
Yes it was a broken link which brought up the problem. (was also marked in UI with yellow exlamation mark). After removing the illegal file the problem vanished.

But should be handled by implementation.
